[package]
cairo-version = "2.1.0"
description = "The Dojo Core library for autonomous worlds."
name = "dojo"
version = "0.2.1"

[dependencies]
dojo_plugin = { git = "https://github.com/derrick-yang/dojo", branch = "starknet_2.1.0"}
starknet = "2.1.0"
